image: docker:stable

before_script:
  - docker info

build-image:
  stage: build
  script:
    - docker build -t spordle:latest .

unit-tests:
  stage: test
  script:
    - docker run --rm spordle:latest /bin/bash -c 'yarn test --watchAll=false'

lint:
  stage: test
  script:
    - docker run --rm spordle:latest /bin/bash -c 'yarn lint'
