name: spordle-merge-request-flow
run-name: Spordle Test Flow 🚀
on: [pull_request]
jobs:
  Lint:
    runs-on: self-hosted
    steps:
      - run: yarn
      - run: yarn lint
  Unit-Tests:
    runs-on: self-hosted
    steps:
      - run: yarn
      - run: yarn test
